import { waitForElement, stripAreaLimitUi } from '../../common/dom.mjs';
import { extractDash, uniqueQualities, uniqueCodecs, audioOptions, createMpdUrl } from './dashMpdBuilder.mjs';
import { createQualityPanel } from './qualityPanel.mjs';
import { startDanmaku } from '../danmaku/engineController.mjs';
export async function mountPlayer({playurl,context,config,log}){ const dash=extractDash(playurl); if(!dash||!dash.video?.length) throw new Error('No DASH video in playurl response'); const target=await waitForElement('#bilibili-player, .bpx-player-container'); const outer=target.id==='bilibili-player'?target:(target.closest('#bilibili-player')||target); outer.style.position='relative'; outer.querySelectorAll('.brx-player-root').forEach(el=>el.remove()); stripAreaLimitUi(outer); const root=document.createElement('div'); root.className='brx-player-root'; root.innerHTML='<div class="brx-video-box"><video class="brx-video" controls playsinline></video><div class="brx-danmaku-layer"></div><div class="brx-status">BiliRoaming-X Player</div></div>'; const style=document.createElement('style'); style.textContent=cssText(); root.appendChild(style); outer.appendChild(root); for(const v of outer.querySelectorAll('video')) if(!v.classList.contains('brx-video')) v.style.opacity='0'; const video=root.querySelector('.brx-video'); const layer=root.querySelector('.brx-danmaku-layer'); const status=root.querySelector('.brx-status'); const qualities=uniqueQualities(dash.video||[]), codecs=uniqueCodecs(dash.video||[]), audios=audioOptions(dash.audio||dash.dolby?.audio||[]); let selection={qn:config.defaultQn||'80',codec:config.defaultCodec||'auto',audioId:config.defaultAudioId||'auto'}; if(!qualities.some(q=>q.id===selection.qn)) selection.qn=qualities[0]?.id||'auto'; const panel=createQualityPanel({qualities,codecs,audios,initial:selection,onChange:reloadWithSelection}); root.appendChild(panel); let dashPlayer=null, mpdObjectUrl=''; await ensureVendorLoaded(log);
  async function loadDash(){ if(dashPlayer){try{dashPlayer.reset()}catch(_){}} if(mpdObjectUrl) URL.revokeObjectURL(mpdObjectUrl); const mpd=createMpdUrl(dash,selection); mpdObjectUrl=mpd.url; dashPlayer=window.dashjs?.MediaPlayer?.().create(); if(!dashPlayer) throw new Error('dash.js not loaded'); dashPlayer.updateSettings({streaming:{buffer:{fastSwitchEnabled:true},abr:{autoSwitchBitrate:{video:selection.qn==='auto'}}}}); dashPlayer.initialize(video,mpdObjectUrl,false); dashPlayer.on(window.dashjs.MediaPlayer.events.ERROR,e=>{status.textContent='播放错误: '+JSON.stringify(e.error||e)}); dashPlayer.on(window.dashjs.MediaPlayer.events.STREAM_INITIALIZED,()=>{status.textContent='DASH 已加载'; setTimeout(()=>status.style.opacity='0',1600);}); }
  async function reloadWithSelection(next){ const t=video.currentTime||0, paused=video.paused; selection=next; await loadDash(); video.addEventListener('loadedmetadata',()=>{video.currentTime=t;if(!paused) video.play().catch(()=>{})},{once:true}); }
  await loadDash(); let dm=null; if(config.danmakuEnabled) dm=await startDanmaku({layer,video,context,config,log}); try{video.play().catch(()=>{})}catch(_){} return {root,video,get dashPlayer(){return dashPlayer},get selection(){return selection},danmaku:dm,destroy(){try{dm?.destroy?.()}catch(_){} try{dashPlayer?.reset?.()}catch(_){} if(mpdObjectUrl) URL.revokeObjectURL(mpdObjectUrl); root.remove();}}; }
async function ensureVendorLoaded(log){ if(!window.dashjs) throw new Error('dash.js content script not loaded'); }
function cssText(){ return `.brx-player-root{position:absolute;inset:0;z-index:999;background:#000;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.brx-video-box{position:absolute;inset:0;background:#000;overflow:hidden}.brx-video{width:100%;height:100%;background:#000;display:block}.brx-danmaku-layer{position:absolute;inset:0;pointer-events:none;z-index:3;overflow:hidden}.brx-status{position:absolute;left:14px;top:12px;z-index:5;background:rgba(0,0,0,.55);padding:6px 10px;border-radius:6px;transition:opacity .35s}.brx-quality-panel{position:absolute;right:12px;top:12px;z-index:6;display:flex;gap:8px;align-items:center;background:rgba(0,0,0,.62);padding:8px;border-radius:8px;backdrop-filter:blur(4px)}.brx-quality-panel label{font-size:12px;color:#fff;display:flex;gap:4px;align-items:center}.brx-quality-panel select{background:#18191c;color:#fff;border:1px solid #555;border-radius:4px;padding:3px 5px}`; }


